# Pre-commit hooks for code quality
# Install with: pip install pre-commit && pre-commit install

repos:
  # Code formatting with Black
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.11
        args: ['--line-length=100']
        exclude: ^(migrations/|\.git/|\.venv/)

  # Linting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        args: ['--fix']
        exclude: ^(migrations/|\.git/|\.venv/)

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args: ['--ignore-missing-imports', '--check-untyped-defs']
        additional_dependencies: ['types-requests', 'types-PyYAML']
        exclude: ^(tests/|migrations/|\.git/|\.venv/)

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ['-ll', '-i', '-r']
        exclude: ^(tests/|migrations/|\.git/|\.venv/)

  # YAML validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-case-conflict

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ['--fix', '--disable', 'MD013', 'MD024', 'MD033']

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile', 'black', '--line-length', '100']

  # Detect common security issues
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

  # Pytest runner
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ['-q', '--tb=short', 'tests/']
        stages: [commit]